apiVersion: v1
kind: Service
metadata:
  name: simple-node-app-clusterip
  namespace: simple-node-app
spec:
  type: ClusterIP # This is the default value
  selector:
    app: simple-node-app
  ports:
    - protocol: TCP
      port: 80 # Port the service is listening on
      targetPort: 3000 # Port the container is listening on (if unset, defaults to equal port value)
