apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-node-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:poppyszn/simple-node-app-manifests.git
    targetRevision: main
    path: simple-node-app/overlays/production
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      enabled: true 
      selfHeal: true 
      allowEmpty: false 