apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-node-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:poppyszn/simple-node-app-manifests.git
    targetRevision: main
    path: simple-node-app/overlays/production
  destination:
    server: https://kubernetes.default.svc
