apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-node-app-ingress
  namespace: simple-node-app
spec:
  ingressClassName: nginx
  rules:
    - host: "prod.vasconsolutionsapp.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-node-app-clusterip
                port:
                  number: 80