apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simple-node-app-prod
resources:
- ../../base
patches:
- path: deployment.yaml
  target:
    kind: Deployment
    name: .*
- path: ingress.yaml
  target:
    kind: Ingress
    name: .*
- path: namespace.yaml
  target:
    kind: Namespace
    name: .*

images:
- name: precious/simple-node-app
  newName: precious/simple-node-app
  newTag: latest
