apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simple-node-app-prod
resources:
- ../../base
patches:
- path: deployment.yaml
  target:
    kind: Deployment
    name: .*
- path: ingress.yaml
  target:
    kind: Ingress
    name: .*
- path: namespace.yaml
  target:
    kind: Namespace
    name: .*

images:
- name: 801244285013.dkr.ecr.eu-west-1.amazonaws.com/precious/simple-node-app
  newName: 801244285013.dkr.ecr.eu-west-1.amazonaws.com/precious/simple-node-app
  newTag: a97b98634b1c83af6acdb885eedf56e0668d5021
- name: precious/simple-node-app
  newTag: e4467f514b78ad56677064aca4bb889c9410649f
